### ISSUE TITLE
User with no curate privilege can suggest edit of status-completed tag (old issue maybe it was resolved)

### ISSUE THREAD

**Issue by b-Istiak-s** [codidact/qpixel#741] opened 2021-12-14 04:08 UTC
Not sure if it's only a bug in Linux Systems. As far as I remember the issue was informed earlier and it was resolved.  

In the following suggest edit, @Trilarion had suggested edit with status-complete tag.

https://linux.codidact.com/posts/suggested-edit/803

**Comment by cellio** [comment] 2021-12-30 20:17
Users can suggest edits of mod-only tags, but only moderators can approve those edits (as I just did here).  We should probably allow the suggestions as we do now but add something to the edit-review page about only mods being able to approve this, so other reviewers don't get weird errors if they try to approve it.

**Comment by Trilarion** [comment] 2021-12-31 08:57
@cellio If a user already had the edit ability but wants to suggest a status-X tag, does it then too become a suggested edit that needs approval by a moderator? Or is it currently impossible for such a user?

**Comment by cellio** [comment] 2021-12-31 16:15
Oh, that's a good point @Trilarion -- I'd bet that we don't catch that case, and we need to.  Ideally it would become a suggested edit, and we'd give some post-submission feedback about that so someone with the Edit ability wouldn't be left wondering why it didn't get applied.

If all of this means it's easier to not allow non-moderators to apply those tags at all (catch it in the editor), that would probably be ok.  If someone tries to add a mod tag and we block it, we should emit a message suggesting the person to flag for a mod to do it instead.

I don't know which approach is better.  Should we bring it up on Meta?

**Comment by Trilarion** [comment] 2022-01-01 11:45
@cellio

Suggesting addition or removal of status-X tags with moderator flags would be more clear, I'd say. We could forbid it completely in edits and hint at moderator flags and if the edit is only that we could even offer to automatically convert it to a moderator flag. I would like that. On meta it could maybe be part of a general post with title "What are status-X tags good for and how to use them?".

**Comment by MoshiKoi** [comment] 2022-01-03 03:24
> @cellio If a user already had the edit ability but wants to suggest a status-X tag, does it then too become a suggested edit that needs approval by a moderator? Or is it currently impossible for such a user?

https://meta.codidact.com/posts/277918

**Comment by Taeir** [comment] 2023-07-21 17:34
Looked into the issue and things seems to be working as intended.

* Normal users can suggest edits with moderator tags
* Only mods can approve those edits.
* If a non-mod tries to approve the edit, they get a clear message that only moderators can add the suggested tag.
* If the moderator tag was already on the post, normal users can suggest (and accept with edit privileges) to add more (non-moderator) tags without issue.

Non-mods with edit permissions lose the ability to suggest edits, so adding/suggesting moderator tags for them becomes impossible. If that is something that should be fixed, I think that should be a separate issue and this one can be closed.

**Comment by cellio** [comment] 2023-08-01 17:09
Fixed with previous PR.

**Closed by cellio** 2023-08-01 17:09 UTC
Labels: area: html/css/js, type: bug, priority: low, complexity: unassessed
