### ISSUE TITLE
Show that (and when) a post was edited

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#78] opened 2020-05-10 21:54 UTC
I often see a post get bumped on the front page, so I can tell that the last activity was by so-and-so at such-and-such time.  But I can't tell any of that from the *question page itself*, and sometimes it's a third-party edit to fix a typo and "look at so-and-so's post there" doesn't apply.

Could we show some last-edited info with posts?  "Last edited $timestamp [by so-and-so]" below the author's usercard would be fine, or maybe there's a better place.  (I don't think we need to show the editor's usercard; I only included the attribution to avoid implying that the author made the edit when that wasn't the case.)

Another approach would be for the "last modified" (or whatever) link on the question list to jump to the modified post, like it does on SE, but I think that's lower priority and wouldn't remove the desire to see it on the page itself.  My request here is just about showing the edit on the post somehow.

**Comment by ArtOfCode-** [comment] 2020-05-30 16:51
Duplicate of #87

**Closed by ArtOfCode-** 2020-05-30 16:51 UTC
Labels: area: frontend, priority: low, type: change request

**Comment by cellio** [comment] 2020-05-31 03:22
Ugh, that was my own duplicate and I missed it!  Sorry.
