### ISSUE TITLE
Return to same page after sign-in

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1129] opened 2023-07-20 01:58 UTC
https://meta.codidact.com/posts/288196

After you sign in, you're directed to the default page for a community, regardless of where you started.  We should remember what page you were on and send you back there, so that if you were, say, about to answer a question, you don't have to go hunting for it again.

https://github.com/codidact/qpixel/pull/1127 might do this for SSO already, but I don't know if it helps in the non-SSO case.

**Comment by MoshiKoi** [comment] 2023-07-20 02:14
Duplicate of #239

**Closed by MoshiKoi** 2023-07-20 02:14 UTC
Labels: area: html/css/js, type: change request, priority: medium, complexity: unassessed
