### ISSUE TITLE
Post editor shows more tags than post/category pages do

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1301] opened 2024-02-01 02:22 UTC
meta:289816

I do not know if this is a one-off data error or if there is an underlying cause that we should address.

Example demonstrating the problem: https://electrical.codidact.com/posts/285721

This post displays one tag, but if you edit the post, the editor shows four tags:

- RF, the single displayed tag
- RF-switch, which the tags page shows with 0 uses
- esd and tvs, which don't exist but ESD and TVS do -- I think these were either merged or renamed

Do we need to do some extra bookkeeping when we merge or rename a tag?  
When the last use of a tag is deleted, should we delete the tag if there is no description?  (I did not confirm that there are no deleted uses of that one tag; I scanned the deletions page but I can't directly search for that in the UI.)  
Would any of that helped in this case?

Or is this a cache problem we can't do anything to prevent in the code and we should just fix cases when found?

**Comment by MoshiKoi** [comment] 2024-02-11 21:47
Duplicate of #268?

**Comment by cellio** [comment] 2024-02-11 21:53
Hmm, maybe -- the description there sounds like the problem goes away in time (caching), and this inconsistency is longer-lived, but maybe the speculation in the description is wrong and it's all the same problem?

**Comment by cellio** [comment] 2024-02-11 21:55
Closed as duplicate.  Added this meta link to the other bug.

**Closed** 2024-02-11 21:54 UTC
Labels: area: ruby, type: bug, type: analysis
