### ISSUE TITLE
qpixel code apparently bakes in codidact.com network in places

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#770] opened 2022-02-10 02:01 UTC
I'm looking at the dev server and I see the network footer on pages, including the list of sites.  A suspension message also included a link to Meta, and I think I saw another Meta link.  If somebody else were to run an instance from our repo, these connections would be confusing or wrong.

Ultimately we should figure out how to separate instance from platform, which probably involves configuration knobs and "plug in your footer here" and stuff.  In the shorter term, can we document what people will need to change?  Is searching the code for "codidact.com" enough to find all the connections and change/remove them?  I don't want this to become an onerous task, but it'd be nice to be able to give people a heads-up and suggestions about what to do about it until we get around to separating them.

**Comment by cellio** [comment] 2022-08-14 20:27
See https://github.com/codidact/qpixel/issues/826#issuecomment-1214395898 for a list of hard-coded Codidact references.

**Comment by MoshiKoi** [comment] 2022-08-16 23:29
> See https://github.com/codidact/qpixel/issues/826#issuecomment-1214395898 for a list of hard-coded Codidact references.

Should we close this as a duplicate of the other issue?

**Comment by cellio** [comment] 2022-08-16 23:36
Good idea.  The other issue has a list of where the hard-coded references are, so let's use that one.

**Closed** 2022-08-16 23:37 UTC
Labels: area: ruby, type: bug, priority: low, complexity: unassessed
